# Generated by Django 4.2.11 on 2024-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=255)),
                ('team2', models.CharField(max_length=255)),
                ('toss_winner', models.CharField(max_length=255)),
                ('toss_decision', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('dl_applied', models.IntegerField()),
                ('winner', models.CharField(max_length=255)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('umpire1', models.CharField(max_length=255)),
                ('umpire2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
    ]
