# Generated by Django 4.2.11 on 2024-04-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField(default=0)),
                ('inning', models.IntegerField(default=0)),
                ('batting_team', models.CharField(default='null', max_length=255)),
                ('bowling_team', models.CharField(default='null', max_length=255)),
                ('over', models.IntegerField(default=0)),
                ('ball', models.IntegerField(default=0)),
                ('batsman', models.CharField(default='null', max_length=255)),
                ('non_striker', models.CharField(default='null', max_length=255)),
                ('bowler', models.CharField(default='null', max_length=255)),
                ('is_super_over', models.IntegerField(default=0)),
                ('wide_runs', models.IntegerField(default=0)),
                ('bye_runs', models.IntegerField(default=0)),
                ('legbye_runs', models.IntegerField(default=0)),
                ('noball_runs', models.IntegerField(default=0)),
                ('penalty_runs', models.IntegerField(default=0)),
                ('batsman_runs', models.IntegerField(default=0)),
                ('extra_runs', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('player_dismissed', models.CharField(default='null', max_length=255)),
                ('dismissal_kind', models.CharField(default='null', max_length=255)),
                ('fielder', models.CharField(default='null', max_length=255)),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=255)),
                ('team2', models.CharField(max_length=255)),
                ('toss_winner', models.CharField(max_length=255)),
                ('toss_decision', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('dl_applied', models.IntegerField()),
                ('winner', models.CharField(max_length=255)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('umpire1', models.CharField(max_length=255)),
                ('umpire2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
    ]
